---
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    access: proxy
    url: http://prometheus:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
    editable: false
    version: 1
