
run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    #- gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    #- noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck
    - gomnd
    - dupl
    - funlen
    - lll
    - goconst

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - sync/atomic
    packages-with-error-message:
      - sync/atomic: "Use go.uber.org/atomic instead of sync/atomic"
  govet:
    # report about shadowed variables
    check-shadowing: true
  funlen:
    lines: 250
    statements: 100
  goconst:
    min-len: 4
    min-occurrences: 4
    ignore-tests: false
    match-constant: true
    numbers: false
    min: 3
    max: 3
    ignore-calls: true
  lll:
    line-length: 185
