---
consumer:
  kind: rabbitmq
  address: 127.0.0.1
  port: 5672
  requestedHeartbeat: 25s
  username: myuser
  password: mypassword
  virtualHost: myvirtualhost
  queue:
    name: my.queue
    routingKey: my.routeKey
    durable: true
    autoDelete: true
    exclusive: false
    args:
      x-message-ttl: 180000
  exchange:
    name: myexchage
    type: topic
    durable: true
    autoDelete: false
    args:
      x-dead-letter-exchange: my.dead_letter

database:
  kind: postgresql
  address: 127.0.0.1
  port: 5432
  username: myusername
  passsword: mypassword
  database: mydatabase
  sslMode: disable
  maxPingTimeOut: 1s
  maxQueryTimeOut: 30s
  connMaxLifetime: 0
  maxIdleConns: 5
  maxOpenConns: 20
