{
 "title": "mq-to-db",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mq_to_db_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{job=~\"mq-to-db\"}) * 1000"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mq_to_db_consumer_running{job=\"mq-to-db\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Storage Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mq_to_db_storage_worker_running{job=\"mq-to-db\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Database Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mq_to_db_database_open_connections{job=\"mq-to-db\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count by (goversion, instance,revision,version) (mq_to_db_build_info)"
    }
   ]
  }
 ]
}