
name: Develop branch workflow

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - develop
    paths-ignore:
      - "**.md"
env:
  GO_VERSION: 1.17

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Show Project Files Before Make
        run: tree .

      - name: Build and Test
        run: make

      - name: Show Project Files After Make
        run: tree .

      - name: Remove artifacts
        run: make clean