
name: Develop branch workflow

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - develop
    paths-ignore:
      - "**.md"

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Git Version
        run: |
          git rev-parse --abbrev-ref HEAD

      - name: Git Revision
        run: |
          git rev-parse HEAD | tr -d '\040\011\012\015\n'

      - name: Git Branch
        run: |
          git rev-parse --abbrev-ref HEAD | tr -d '\040\011\012\015\n'

      - name: Git User
        run: |
          git config --get user.name | tr -d '\040\011\012\015\n'

      - name: Show Project Files Before Make
        run: tree .

      - name: Build and Test
        run: make

      - name: Show Project Files After Make
        run: tree .

      - name: Remove artifacts
        run: make clean