name: Master branch workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

env:
  DOCKER_BUILD_ARCHS: "amd64"
  DOCKER_HUB_REPO: "docker.io/christiangda"
  GH_PACKAGE_REPO: "docker.pkg.github.com/christiangda/mq-to-db"
  GO_VERSION: 1.18

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test Linux Platform Only
        run: make test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Git Version
        run: |
          git rev-parse --abbrev-ref HEAD

      - name: Git Revision
        run: |
          git rev-parse HEAD | tr -d '\040\011\012\015\n'

      - name: Git Branch
        run: |
          git rev-parse --abbrev-ref HEAD | tr -d '\040\011\012\015\n'

      - name: Git User
        run: |
          git config --get user.name | tr -d '\040\011\012\015\n'

      - name: Build
        run: make

      - name: List Workspace Files
        run: tree .