name: Release workflow

on:
  push:
    tags:
      - v[012].[0-9]+.[0-9]+ # https://help.github.com/es/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

env:
  DOCKER_BUILD_ARCHS: "amd64"
  DOCKER_HUB_REPO: "docker.io/christiangda"
  GH_PACKAGE_REPO: "docker.pkg.github.com/christiangda/mq-to-db"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test
        run: make test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Git Current Tag Version
        run: |
          echo GIT_VERSION=${{ github.ref_name }}

      - name: Git Version
        run: |
          git rev-parse --abbrev-ref HEAD

      - name: Git Revision
        run: |
          git rev-parse HEAD | tr -d '\040\011\012\015\n'

      - name: Git Branch
        run: |
          git rev-parse --abbrev-ref HEAD | tr -d '\040\011\012\015\n'

      - name: Git User
        run: |
          git config --get user.name | tr -d '\040\011\012\015\n'

      - name: Build Distribution Cross-Platform
        run: GIT_VERSION=${{ github.ref_name }} make build-dist

      - name: List Workspace Files
        run: tree .

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/

  publish_docker_images:
    name: Publish Docker Images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Docker Version
        run: docker version

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/

      - name: List Workspace Files
        run: tree .

      - name: Build Docker Images for docker hub
        run: make container-build CONTAINER_REPO=${{ env.DOCKER_HUB_REPO }} CONTAINER_ARCH=${{ env.DOCKER_BUILD_ARCHS }} GIT_VERSION=${{ github.ref_name }}

      - name: Show Local Docker Images
        run: docker images

      - name: Logging in Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Publish Images in Docker Hub
        run: make container-publish-docker CONTAINER_REPO=${{ env.DOCKER_HUB_REPO }} CONTAINER_ARCH=${{ env.DOCKER_BUILD_ARCHS }} GIT_VERSION=${{ github.ref_name }}

      # - name: Logging in GitHub Packages
      #   run: echo ${{ secrets.GH_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.GH_USER }} --password-stdin

      # - name: Publish Images in GitHub Packages
      #   run: make container-publish-github CONTAINER_REPO=${{ env.DOCKER_HUB_REPO }} CONTAINER_ARCH=${{ env.DOCKER_BUILD_ARCHS }} GIT_VERSION=${{ github.ref_name }}

  create_github_release:
    name: Create Github Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/

      - name: Show workspace files
        run: tree .

      - name: Create Release
        id: create_github_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # body: |
          #   See the file: CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_github_release.outputs.id }}
          assets_path: dist/assets